export default {
  LAYOUTHEADER_MENU_PRODUCTS: "产品与服务",
  LAYOUTHEADER_MENU_DOCUMENTS: "文档",
  LAYOUTHEADER_MENU_PRICES: "价格",
  LAYOUTHEADER_MENU_CONTACTS: "联系我们",
  LANGUAGE_ZH: "中文",
  LANGUAGE_EN: "English",
  LANGUAGE_JA: "日本語",
  BUTTON_START: "开始使用",
  FOOTER_HElPCENTER: "帮助中心",
  FOOTER_MANUAL: "用户手册",
  FOOTER_CONRTACT: "联系我们",
  FOOTER_EMAIL: "邮件：",
  FOOTER_TIME: "办公时间：工作日  上午9:00 - 12:00 ｜ 下午13:30 - 6:00",
  PRICES_TITLE: "EASE-PAAS 私有化部署",
  PRICES_DESC:
    "通过 EASE-PAAS 的私有化部署一键构建私有云，全面支撑企业各类应用需求且维护成本极低，快速响应数字变革需求。",
  PRICES_BASIC_TITLE: "标准版",
  PRICES_BASIC_DESC: "适合开发者测试，或 POC demo",
  PRICES_BASIC_LIST_ITEM1: "多租户",
  PRICES_BASIC_LIST_ITEM2: "应用市场",
  PRICES_BASIC_LIST_ITEM3: "服务商中心",
  PRICES_BASIC_LIST_ITEM4: "权限管理",
  PRICES_BASIC_LIST_ITEM5: "工单服务",
  PRICES_BASIC_LIST_ITEM6: "计量/配额",
  PRICES_BASIC_LIST_ITEM7: "开发中间件",
  PRICES_BASIC_BUTTON: "注册体验",
  PRICES_ENTERPRISE_TITLE: "企业版",
  PRICES_ENTERPRISE_DESC: "适合企业生产环境",
  PRICES_ENTERPRISE_LIST_ITEM1: "私有化部署",
  PRICES_ENTERPRISE_LIST_ITEM2: "工作日8h内响应",
  PRICES_ENTERPRISE_LIST_ITEM3: "多租户",
  PRICES_ENTERPRISE_LIST_ITEM4: "应用市场",
  PRICES_ENTERPRISE_LIST_ITEM5: "服务商中心",
  PRICES_ENTERPRISE_LIST_ITEM6: "权限管理",
  PRICES_ENTERPRISE_LIST_ITEM7: "工单服务",
  PRICES_ENTERPRISE_LIST_ITEM8: "计量/配额",
  PRICES_ENTERPRISE_LIST_ITEM9: "开发中间件",
  PRICES_ENTERPRISE_BUTTON: "联系我们",
  PRICES_CUSTOMIZED_TITLE: "定制版",
  PRICES_CUSTOMIZED_DESC: "适合大规模集群与大型企业客户",
  PRICES_CUSTOMIZED_LIST_ITEM1: "定制化开发与源码级交付",
  PRICES_CUSTOMIZED_LIST_ITEM2: "超大规模集群",
  PRICES_CUSTOMIZED_LIST_ITEM3: "私有化部署",
  PRICES_CUSTOMIZED_LIST_ITEM4: "工作日8h内响应",
  PRICES_CUSTOMIZED_LIST_ITEM5: "多租户",
  PRICES_CUSTOMIZED_LIST_ITEM6: "应用市场",
  PRICES_CUSTOMIZED_LIST_ITEM7: "服务商中心",
  PRICES_CUSTOMIZED_LIST_ITEM8: "权限管理",
  PRICES_CUSTOMIZED_LIST_ITEM9: "工单服务",
  PRICES_CUSTOMIZED_LIST_ITEM10: "计量/配额",
  PRICES_CUSTOMIZED_LIST_ITEM11: "开发中间件",
  PRICES_CUSTOMIZED_BUTTON: "联系我们",
  CONTACT_TITLE: "EASE-PAAS 商务咨询",
  CONTACT_NAME: "姓名",
  CONTACT_ENTERPRISE: "公司名称",
  CONTACT_EMAIL: "公司邮箱",
  CONTACT_PRODUCTREQUIRE: "您对产品的需求是？",
  CONTACT_OPTION1: "希望私有化部署",
  CONTACT_OPTION2: "希望定制化开发",
  CONTACT_OPTION3: "希望源码交付",
  CONTACT_OPTION4: "其它",
  CONTACT_SAYTOUS: "其它想对我们说的？",
  CONTACT_INPUT_PLACEHOLDER: "请输入",
  CONTACT_INPUT_EMAIL_ERROR: "请输入正确的邮箱地址",
  CONTACT_BUTTON: "提交",
  INDEX_TITLE: "数字化基础底座：EASE-PaaS",
  INDEX_TITLE_DEFAULT_1: "覆盖<span>三大场景</span>",
  INDEX_DESC_1: "打造灵活的组织全县管理方式和便捷的多应用协同办公体验",
  INDEX_ITEM1_TITLE: "sso集成",
  INDEX_ITEM1_CHILD_1: "统一认证授权框架",
  INDEX_ITEM1_CHILD_2: "方便的管理员工与部门权限",
  INDEX_ITEM1_CHILD_3: "企业应用商店",
  INDEX_ITEM2_TITLE: "B2B 支撑底座",
  INDEX_ITEM2_CHILD_1:
    "围绕核心应用快速构建B2B 平台, 内置账单，支付，消息通知等功能",
  INDEX_ITEM2_CHILD_2: "管理租户的权限和授权租户自管理",
  INDEX_ITEM2_CHILD_3: "可基于租户，用户的规模方便的扩容",
  INDEX_ITEM3_TITLE: "聚合众多应用形成特定业务领域内的应用生态圈",
  INDEX_ITEM3_CHILD_1:
    "聚合企业自己与合作伙伴的应用，围绕一个业务领域，快速形成应用平台",
  INDEX_ITEM3_CHILD_2: "合作伙伴以软件供应商的身份申请上架应用",
  INDEX_ITEM3_CHILD_3: "运营组织审核应用上架申请，管理合作伙伴组织与客户组织",
  INDEX_TITLE_DEFAULT_2:
    "以<span>Kubernetes+IAM</span>为核心的云原生的解决方案",
  INDEX_DESC_2: "一站式解决多应用、多租户、统一认证授权、统一运维带来的挑战",
  ECOSPHERE_ITEM1: "租户",
  ECOSPHERE_ITEM2: "生态伙伴",
  ECOSPHERE_ITEM3: "服务商",
  ECOSPHERE_ITEM4: "平台及应用生态圈",
  ECOSPHERE_ITEM5: "开放能力",
  ECOSPHERE_ITEM6: "基础能力",
  ECOSPHERE_ITEM7: "多租户容器管理",
  ECOSPHERE_ITEM8: "统一授权中心",
  PRODUCTBENEFITS_TITLE: "产品效益",
  PRODUCTBENEFITS_ITEM1:
    "一周时间打通企业内部应用的认证授权，更安全，更及时的管理企业内部应用资源。",
  PRODUCTBENEFITS_ITEM2: "数周时间，而不是数月时间上线自己的B2B应用分发平台。",
  PRODUCTBENEFITS_ITEM3:
    "在平台上集成自己与合作伙伴的应用，一个月交付给客户一个综合解决方案。",
  INDEX_TITLE_DEFAULT_3: "如何开始",
  INDEX_TITLE_DEFAULT_4: "为什么选择我们",
  REASON_ITEM1_TITLE: "最强大的B2B应用超市平台",
  REASON_ITEM1_DESC:
    "在统一的云原生基础设施上，快速集成您自己的和合作伙伴的应用，开放给众多客户组织订阅使用。",
  REASON_ITEM2_TITLE: "丰富的落地案例",
  REASON_ITEM2_DESC:
    "我们已经帮助众多客户在能源，教育，化工，ESG，碳排放管理建设了自己的应用平台。",
  REASON_ITEM3_TITLE: "可定制化开发",
  REASON_ITEM3_DESC:
    "可以提供定制化功能开发，满足客户特定需求，定制化集成客户的应用。",
  REASON_ITEM4_TITLE: "可私有化部署",
  REASON_ITEM4_DESC: "可以部署在客户的私有云。",
  START_BTN_1: "访问",
  START_TITLE: "注册成为租户管理员，邀请并管理企业成员。",
  START_DESC_1: "使用应用市场demo应用，了解产品功能。",
  START_DESC_2: "申请开通专属实例，以运营管理员的身份试用产品的全部功能。",
  START_DESC_3: "在专属实例里，自己和合作伙伴集成新的应用到应用市场。",
  START_DESC_4:
    "在专属实例里，为客户企业创建组织，管理客户订阅应用市场里的丰富应用。",
  START_BTN_2: "使用",
  HEADER_CHILD_MENU1_TITLE: "交付与服务",
  HEADER_CHILD_MENU1_ITEM_1: "定制化开发",
  HEADER_CHILD_MENU1_ITEM_2: "源代码交付",
  HEADER_CHILD_MENU1_ITEM_3: "生态应用集成",
  HEADER_CHILD_MENU2_TITLE: "应用产品",
  HEADER_CHILD_MENU2_ITEM_1: "IAM",
  HEADER_CHILD_MENU2_ITEM_2: "双碳",
  HEADER_CHILD_MENU2_ITEM_3: "ESG",
};
